// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wysteria.grpc.proto

/*
Package wysteria_grpc is a generated protocol buffer package.

It is generated from these files:
	wysteria.grpc.proto

It has these top-level messages:
	IdAndNum
	IdAndDict
	Id
	Text
	Collection
	Item
	Version
	Resource
	Link
	QueryDesc
	QueryDescs
	Ids
	Collections
	Items
	Versions
	Resources
	Links
*/
package wysteria_grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IdAndNum struct {
	Id      string `protobuf:"bytes,96,opt,name=Id" json:"Id,omitempty"`
	Version int32  `protobuf:"varint,100,opt,name=Version" json:"Version,omitempty"`
	Text    string `protobuf:"bytes,101,opt,name=Text" json:"Text,omitempty"`
}

func (m *IdAndNum) Reset()                    { *m = IdAndNum{} }
func (m *IdAndNum) String() string            { return proto.CompactTextString(m) }
func (*IdAndNum) ProtoMessage()               {}
func (*IdAndNum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IdAndNum) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IdAndNum) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *IdAndNum) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type IdAndDict struct {
	Id     string            `protobuf:"bytes,96,opt,name=Id" json:"Id,omitempty"`
	Facets map[string]string `protobuf:"bytes,97,rep,name=Facets" json:"Facets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *IdAndDict) Reset()                    { *m = IdAndDict{} }
func (m *IdAndDict) String() string            { return proto.CompactTextString(m) }
func (*IdAndDict) ProtoMessage()               {}
func (*IdAndDict) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IdAndDict) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IdAndDict) GetFacets() map[string]string {
	if m != nil {
		return m.Facets
	}
	return nil
}

type Id struct {
	Id    string `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Error *Text  `protobuf:"bytes,81,opt,name=error" json:"error,omitempty"`
}

func (m *Id) Reset()                    { *m = Id{} }
func (m *Id) String() string            { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()               {}
func (*Id) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Id) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Id) GetError() *Text {
	if m != nil {
		return m.Error
	}
	return nil
}

type Text struct {
	Text string `protobuf:"bytes,80,opt,name=Text" json:"Text,omitempty"`
}

func (m *Text) Reset()                    { *m = Text{} }
func (m *Text) String() string            { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()               {}
func (*Text) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Text) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Collection struct {
	Parent string            `protobuf:"bytes,95,opt,name=Parent" json:"Parent,omitempty"`
	Id     string            `protobuf:"bytes,6,opt,name=Id" json:"Id,omitempty"`
	Name   string            `protobuf:"bytes,7,opt,name=Name" json:"Name,omitempty"`
	Facets map[string]string `protobuf:"bytes,94,rep,name=Facets" json:"Facets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error  *Text             `protobuf:"bytes,82,opt,name=error" json:"error,omitempty"`
}

func (m *Collection) Reset()                    { *m = Collection{} }
func (m *Collection) String() string            { return proto.CompactTextString(m) }
func (*Collection) ProtoMessage()               {}
func (*Collection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Collection) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Collection) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Collection) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Collection) GetFacets() map[string]string {
	if m != nil {
		return m.Facets
	}
	return nil
}

func (m *Collection) GetError() *Text {
	if m != nil {
		return m.Error
	}
	return nil
}

type Item struct {
	Parent   string            `protobuf:"bytes,12,opt,name=Parent" json:"Parent,omitempty"`
	Id       string            `protobuf:"bytes,13,opt,name=Id" json:"Id,omitempty"`
	ItemType string            `protobuf:"bytes,14,opt,name=ItemType" json:"ItemType,omitempty"`
	Variant  string            `protobuf:"bytes,15,opt,name=Variant" json:"Variant,omitempty"`
	Facets   map[string]string `protobuf:"bytes,16,rep,name=Facets" json:"Facets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error    *Text             `protobuf:"bytes,83,opt,name=error" json:"error,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Item) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetItemType() string {
	if m != nil {
		return m.ItemType
	}
	return ""
}

func (m *Item) GetVariant() string {
	if m != nil {
		return m.Variant
	}
	return ""
}

func (m *Item) GetFacets() map[string]string {
	if m != nil {
		return m.Facets
	}
	return nil
}

func (m *Item) GetError() *Text {
	if m != nil {
		return m.Error
	}
	return nil
}

type Version struct {
	Parent string            `protobuf:"bytes,25,opt,name=Parent" json:"Parent,omitempty"`
	Id     string            `protobuf:"bytes,26,opt,name=Id" json:"Id,omitempty"`
	Number int32             `protobuf:"varint,27,opt,name=Number" json:"Number,omitempty"`
	Facets map[string]string `protobuf:"bytes,29,rep,name=Facets" json:"Facets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error  *Text             `protobuf:"bytes,84,opt,name=error" json:"error,omitempty"`
}

func (m *Version) Reset()                    { *m = Version{} }
func (m *Version) String() string            { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()               {}
func (*Version) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Version) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Version) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Version) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Version) GetFacets() map[string]string {
	if m != nil {
		return m.Facets
	}
	return nil
}

func (m *Version) GetError() *Text {
	if m != nil {
		return m.Error
	}
	return nil
}

type Resource struct {
	Parent       string            `protobuf:"bytes,36,opt,name=Parent" json:"Parent,omitempty"`
	Name         string            `protobuf:"bytes,37,opt,name=Name" json:"Name,omitempty"`
	ResourceType string            `protobuf:"bytes,38,opt,name=ResourceType" json:"ResourceType,omitempty"`
	Id           string            `protobuf:"bytes,39,opt,name=Id" json:"Id,omitempty"`
	Location     string            `protobuf:"bytes,40,opt,name=Location" json:"Location,omitempty"`
	Facets       map[string]string `protobuf:"bytes,102,rep,name=Facets" json:"Facets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error        *Text             `protobuf:"bytes,85,opt,name=error" json:"error,omitempty"`
}

func (m *Resource) Reset()                    { *m = Resource{} }
func (m *Resource) String() string            { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()               {}
func (*Resource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Resource) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resource) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *Resource) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Resource) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Resource) GetFacets() map[string]string {
	if m != nil {
		return m.Facets
	}
	return nil
}

func (m *Resource) GetError() *Text {
	if m != nil {
		return m.Error
	}
	return nil
}

type Link struct {
	Name   string            `protobuf:"bytes,43,opt,name=Name" json:"Name,omitempty"`
	Id     string            `protobuf:"bytes,44,opt,name=Id" json:"Id,omitempty"`
	Src    string            `protobuf:"bytes,45,opt,name=Src" json:"Src,omitempty"`
	Dst    string            `protobuf:"bytes,46,opt,name=Dst" json:"Dst,omitempty"`
	Facets map[string]string `protobuf:"bytes,103,rep,name=Facets" json:"Facets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error  *Text             `protobuf:"bytes,85,opt,name=error" json:"error,omitempty"`
}

func (m *Link) Reset()                    { *m = Link{} }
func (m *Link) String() string            { return proto.CompactTextString(m) }
func (*Link) ProtoMessage()               {}
func (*Link) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Link) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Link) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Link) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *Link) GetDst() string {
	if m != nil {
		return m.Dst
	}
	return ""
}

func (m *Link) GetFacets() map[string]string {
	if m != nil {
		return m.Facets
	}
	return nil
}

func (m *Link) GetError() *Text {
	if m != nil {
		return m.Error
	}
	return nil
}

type QueryDesc struct {
	Parent        string            `protobuf:"bytes,60,opt,name=Parent" json:"Parent,omitempty"`
	Id            string            `protobuf:"bytes,61,opt,name=Id" json:"Id,omitempty"`
	VersionNumber int32             `protobuf:"varint,62,opt,name=VersionNumber" json:"VersionNumber,omitempty"`
	ItemType      string            `protobuf:"bytes,63,opt,name=ItemType" json:"ItemType,omitempty"`
	Variant       string            `protobuf:"bytes,64,opt,name=Variant" json:"Variant,omitempty"`
	Facets        map[string]string `protobuf:"bytes,65,rep,name=Facets" json:"Facets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Name          string            `protobuf:"bytes,66,opt,name=Name" json:"Name,omitempty"`
	ResourceType  string            `protobuf:"bytes,67,opt,name=ResourceType" json:"ResourceType,omitempty"`
	Location      string            `protobuf:"bytes,68,opt,name=Location" json:"Location,omitempty"`
	LinkSrc       string            `protobuf:"bytes,69,opt,name=LinkSrc" json:"LinkSrc,omitempty"`
	LinkDst       string            `protobuf:"bytes,70,opt,name=LinkDst" json:"LinkDst,omitempty"`
}

func (m *QueryDesc) Reset()                    { *m = QueryDesc{} }
func (m *QueryDesc) String() string            { return proto.CompactTextString(m) }
func (*QueryDesc) ProtoMessage()               {}
func (*QueryDesc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *QueryDesc) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *QueryDesc) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueryDesc) GetVersionNumber() int32 {
	if m != nil {
		return m.VersionNumber
	}
	return 0
}

func (m *QueryDesc) GetItemType() string {
	if m != nil {
		return m.ItemType
	}
	return ""
}

func (m *QueryDesc) GetVariant() string {
	if m != nil {
		return m.Variant
	}
	return ""
}

func (m *QueryDesc) GetFacets() map[string]string {
	if m != nil {
		return m.Facets
	}
	return nil
}

func (m *QueryDesc) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *QueryDesc) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *QueryDesc) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *QueryDesc) GetLinkSrc() string {
	if m != nil {
		return m.LinkSrc
	}
	return ""
}

func (m *QueryDesc) GetLinkDst() string {
	if m != nil {
		return m.LinkDst
	}
	return ""
}

type QueryDescs struct {
	Limit  int32        `protobuf:"varint,105,opt,name=Limit" json:"Limit,omitempty"`
	Offset int32        `protobuf:"varint,106,opt,name=Offset" json:"Offset,omitempty"`
	All    []*QueryDesc `protobuf:"bytes,75,rep,name=all" json:"all,omitempty"`
}

func (m *QueryDescs) Reset()                    { *m = QueryDescs{} }
func (m *QueryDescs) String() string            { return proto.CompactTextString(m) }
func (*QueryDescs) ProtoMessage()               {}
func (*QueryDescs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *QueryDescs) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QueryDescs) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *QueryDescs) GetAll() []*QueryDesc {
	if m != nil {
		return m.All
	}
	return nil
}

type Ids struct {
	All   []*Id `protobuf:"bytes,50,rep,name=all" json:"all,omitempty"`
	Error *Text `protobuf:"bytes,88,opt,name=error" json:"error,omitempty"`
}

func (m *Ids) Reset()                    { *m = Ids{} }
func (m *Ids) String() string            { return proto.CompactTextString(m) }
func (*Ids) ProtoMessage()               {}
func (*Ids) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Ids) GetAll() []*Id {
	if m != nil {
		return m.All
	}
	return nil
}

func (m *Ids) GetError() *Text {
	if m != nil {
		return m.Error
	}
	return nil
}

type Collections struct {
	All   []*Collection `protobuf:"bytes,51,rep,name=all" json:"all,omitempty"`
	Error *Text         `protobuf:"bytes,89,opt,name=error" json:"error,omitempty"`
}

func (m *Collections) Reset()                    { *m = Collections{} }
func (m *Collections) String() string            { return proto.CompactTextString(m) }
func (*Collections) ProtoMessage()               {}
func (*Collections) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Collections) GetAll() []*Collection {
	if m != nil {
		return m.All
	}
	return nil
}

func (m *Collections) GetError() *Text {
	if m != nil {
		return m.Error
	}
	return nil
}

type Items struct {
	All   []*Item `protobuf:"bytes,52,rep,name=all" json:"all,omitempty"`
	Error *Text   `protobuf:"bytes,90,opt,name=error" json:"error,omitempty"`
}

func (m *Items) Reset()                    { *m = Items{} }
func (m *Items) String() string            { return proto.CompactTextString(m) }
func (*Items) ProtoMessage()               {}
func (*Items) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Items) GetAll() []*Item {
	if m != nil {
		return m.All
	}
	return nil
}

func (m *Items) GetError() *Text {
	if m != nil {
		return m.Error
	}
	return nil
}

type Versions struct {
	All   []*Version `protobuf:"bytes,53,rep,name=all" json:"all,omitempty"`
	Error *Text      `protobuf:"bytes,91,opt,name=error" json:"error,omitempty"`
}

func (m *Versions) Reset()                    { *m = Versions{} }
func (m *Versions) String() string            { return proto.CompactTextString(m) }
func (*Versions) ProtoMessage()               {}
func (*Versions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *Versions) GetAll() []*Version {
	if m != nil {
		return m.All
	}
	return nil
}

func (m *Versions) GetError() *Text {
	if m != nil {
		return m.Error
	}
	return nil
}

type Resources struct {
	All   []*Resource `protobuf:"bytes,54,rep,name=all" json:"all,omitempty"`
	Error *Text       `protobuf:"bytes,92,opt,name=error" json:"error,omitempty"`
}

func (m *Resources) Reset()                    { *m = Resources{} }
func (m *Resources) String() string            { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()               {}
func (*Resources) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Resources) GetAll() []*Resource {
	if m != nil {
		return m.All
	}
	return nil
}

func (m *Resources) GetError() *Text {
	if m != nil {
		return m.Error
	}
	return nil
}

type Links struct {
	All   []*Link `protobuf:"bytes,55,rep,name=all" json:"all,omitempty"`
	Error *Text   `protobuf:"bytes,93,opt,name=error" json:"error,omitempty"`
}

func (m *Links) Reset()                    { *m = Links{} }
func (m *Links) String() string            { return proto.CompactTextString(m) }
func (*Links) ProtoMessage()               {}
func (*Links) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *Links) GetAll() []*Link {
	if m != nil {
		return m.All
	}
	return nil
}

func (m *Links) GetError() *Text {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*IdAndNum)(nil), "wysteria_grpc.IdAndNum")
	proto.RegisterType((*IdAndDict)(nil), "wysteria_grpc.IdAndDict")
	proto.RegisterType((*Id)(nil), "wysteria_grpc.Id")
	proto.RegisterType((*Text)(nil), "wysteria_grpc.Text")
	proto.RegisterType((*Collection)(nil), "wysteria_grpc.Collection")
	proto.RegisterType((*Item)(nil), "wysteria_grpc.Item")
	proto.RegisterType((*Version)(nil), "wysteria_grpc.Version")
	proto.RegisterType((*Resource)(nil), "wysteria_grpc.Resource")
	proto.RegisterType((*Link)(nil), "wysteria_grpc.Link")
	proto.RegisterType((*QueryDesc)(nil), "wysteria_grpc.QueryDesc")
	proto.RegisterType((*QueryDescs)(nil), "wysteria_grpc.QueryDescs")
	proto.RegisterType((*Ids)(nil), "wysteria_grpc.Ids")
	proto.RegisterType((*Collections)(nil), "wysteria_grpc.Collections")
	proto.RegisterType((*Items)(nil), "wysteria_grpc.Items")
	proto.RegisterType((*Versions)(nil), "wysteria_grpc.Versions")
	proto.RegisterType((*Resources)(nil), "wysteria_grpc.Resources")
	proto.RegisterType((*Links)(nil), "wysteria_grpc.Links")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WysteriaGrpc service

type WysteriaGrpcClient interface {
	CreateCollection(ctx context.Context, in *Collection, opts ...grpc.CallOption) (*Id, error)
	CreateItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Id, error)
	CreateVersion(ctx context.Context, in *Version, opts ...grpc.CallOption) (*IdAndNum, error)
	CreateResource(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*Id, error)
	CreateLink(ctx context.Context, in *Link, opts ...grpc.CallOption) (*Id, error)
	DeleteCollection(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Text, error)
	DeleteItem(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Text, error)
	DeleteVersion(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Text, error)
	DeleteResource(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Text, error)
	FindCollections(ctx context.Context, in *QueryDescs, opts ...grpc.CallOption) (*Collections, error)
	FindItems(ctx context.Context, in *QueryDescs, opts ...grpc.CallOption) (*Items, error)
	FindVersions(ctx context.Context, in *QueryDescs, opts ...grpc.CallOption) (*Versions, error)
	FindResources(ctx context.Context, in *QueryDescs, opts ...grpc.CallOption) (*Resources, error)
	FindLinks(ctx context.Context, in *QueryDescs, opts ...grpc.CallOption) (*Links, error)
	PublishedVersion(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Version, error)
	SetPublishedVersion(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Text, error)
	UpdateVersionFacets(ctx context.Context, in *IdAndDict, opts ...grpc.CallOption) (*Text, error)
	UpdateItemFacets(ctx context.Context, in *IdAndDict, opts ...grpc.CallOption) (*Text, error)
	UpdateCollectionFacets(ctx context.Context, in *IdAndDict, opts ...grpc.CallOption) (*Text, error)
	UpdateResourceFacets(ctx context.Context, in *IdAndDict, opts ...grpc.CallOption) (*Text, error)
	UpdateLinkFacets(ctx context.Context, in *IdAndDict, opts ...grpc.CallOption) (*Text, error)
}

type wysteriaGrpcClient struct {
	cc *grpc.ClientConn
}

func NewWysteriaGrpcClient(cc *grpc.ClientConn) WysteriaGrpcClient {
	return &wysteriaGrpcClient{cc}
}

func (c *wysteriaGrpcClient) CreateCollection(ctx context.Context, in *Collection, opts ...grpc.CallOption) (*Id, error) {
	out := new(Id)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/CreateCollection", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) CreateItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Id, error) {
	out := new(Id)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/CreateItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) CreateVersion(ctx context.Context, in *Version, opts ...grpc.CallOption) (*IdAndNum, error) {
	out := new(IdAndNum)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/CreateVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) CreateResource(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*Id, error) {
	out := new(Id)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/CreateResource", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) CreateLink(ctx context.Context, in *Link, opts ...grpc.CallOption) (*Id, error) {
	out := new(Id)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/CreateLink", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) DeleteCollection(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Text, error) {
	out := new(Text)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/DeleteCollection", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) DeleteItem(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Text, error) {
	out := new(Text)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/DeleteItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) DeleteVersion(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Text, error) {
	out := new(Text)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/DeleteVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) DeleteResource(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Text, error) {
	out := new(Text)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/DeleteResource", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) FindCollections(ctx context.Context, in *QueryDescs, opts ...grpc.CallOption) (*Collections, error) {
	out := new(Collections)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/FindCollections", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) FindItems(ctx context.Context, in *QueryDescs, opts ...grpc.CallOption) (*Items, error) {
	out := new(Items)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/FindItems", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) FindVersions(ctx context.Context, in *QueryDescs, opts ...grpc.CallOption) (*Versions, error) {
	out := new(Versions)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/FindVersions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) FindResources(ctx context.Context, in *QueryDescs, opts ...grpc.CallOption) (*Resources, error) {
	out := new(Resources)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/FindResources", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) FindLinks(ctx context.Context, in *QueryDescs, opts ...grpc.CallOption) (*Links, error) {
	out := new(Links)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/FindLinks", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) PublishedVersion(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Version, error) {
	out := new(Version)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/PublishedVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) SetPublishedVersion(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Text, error) {
	out := new(Text)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/SetPublishedVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) UpdateVersionFacets(ctx context.Context, in *IdAndDict, opts ...grpc.CallOption) (*Text, error) {
	out := new(Text)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/UpdateVersionFacets", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) UpdateItemFacets(ctx context.Context, in *IdAndDict, opts ...grpc.CallOption) (*Text, error) {
	out := new(Text)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/UpdateItemFacets", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) UpdateCollectionFacets(ctx context.Context, in *IdAndDict, opts ...grpc.CallOption) (*Text, error) {
	out := new(Text)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/UpdateCollectionFacets", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) UpdateResourceFacets(ctx context.Context, in *IdAndDict, opts ...grpc.CallOption) (*Text, error) {
	out := new(Text)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/UpdateResourceFacets", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wysteriaGrpcClient) UpdateLinkFacets(ctx context.Context, in *IdAndDict, opts ...grpc.CallOption) (*Text, error) {
	out := new(Text)
	err := grpc.Invoke(ctx, "/wysteria_grpc.WysteriaGrpc/UpdateLinkFacets", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WysteriaGrpc service

type WysteriaGrpcServer interface {
	CreateCollection(context.Context, *Collection) (*Id, error)
	CreateItem(context.Context, *Item) (*Id, error)
	CreateVersion(context.Context, *Version) (*IdAndNum, error)
	CreateResource(context.Context, *Resource) (*Id, error)
	CreateLink(context.Context, *Link) (*Id, error)
	DeleteCollection(context.Context, *Id) (*Text, error)
	DeleteItem(context.Context, *Id) (*Text, error)
	DeleteVersion(context.Context, *Id) (*Text, error)
	DeleteResource(context.Context, *Id) (*Text, error)
	FindCollections(context.Context, *QueryDescs) (*Collections, error)
	FindItems(context.Context, *QueryDescs) (*Items, error)
	FindVersions(context.Context, *QueryDescs) (*Versions, error)
	FindResources(context.Context, *QueryDescs) (*Resources, error)
	FindLinks(context.Context, *QueryDescs) (*Links, error)
	PublishedVersion(context.Context, *Id) (*Version, error)
	SetPublishedVersion(context.Context, *Id) (*Text, error)
	UpdateVersionFacets(context.Context, *IdAndDict) (*Text, error)
	UpdateItemFacets(context.Context, *IdAndDict) (*Text, error)
	UpdateCollectionFacets(context.Context, *IdAndDict) (*Text, error)
	UpdateResourceFacets(context.Context, *IdAndDict) (*Text, error)
	UpdateLinkFacets(context.Context, *IdAndDict) (*Text, error)
}

func RegisterWysteriaGrpcServer(s *grpc.Server, srv WysteriaGrpcServer) {
	s.RegisterService(&_WysteriaGrpc_serviceDesc, srv)
}

func _WysteriaGrpc_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Collection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/CreateCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).CreateCollection(ctx, req.(*Collection))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/CreateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).CreateItem(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_CreateVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Version)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).CreateVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/CreateVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).CreateVersion(ctx, req.(*Version))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_CreateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Resource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).CreateResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/CreateResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).CreateResource(ctx, req.(*Resource))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_CreateLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Link)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).CreateLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/CreateLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).CreateLink(ctx, req.(*Link))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_DeleteCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).DeleteCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/DeleteCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).DeleteCollection(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/DeleteItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).DeleteItem(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_DeleteVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).DeleteVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/DeleteVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).DeleteVersion(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_DeleteResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).DeleteResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/DeleteResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).DeleteResource(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_FindCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDescs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).FindCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/FindCollections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).FindCollections(ctx, req.(*QueryDescs))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_FindItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDescs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).FindItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/FindItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).FindItems(ctx, req.(*QueryDescs))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_FindVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDescs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).FindVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/FindVersions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).FindVersions(ctx, req.(*QueryDescs))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_FindResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDescs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).FindResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/FindResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).FindResources(ctx, req.(*QueryDescs))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_FindLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDescs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).FindLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/FindLinks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).FindLinks(ctx, req.(*QueryDescs))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_PublishedVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).PublishedVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/PublishedVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).PublishedVersion(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_SetPublishedVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).SetPublishedVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/SetPublishedVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).SetPublishedVersion(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_UpdateVersionFacets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdAndDict)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).UpdateVersionFacets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/UpdateVersionFacets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).UpdateVersionFacets(ctx, req.(*IdAndDict))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_UpdateItemFacets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdAndDict)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).UpdateItemFacets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/UpdateItemFacets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).UpdateItemFacets(ctx, req.(*IdAndDict))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_UpdateCollectionFacets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdAndDict)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).UpdateCollectionFacets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/UpdateCollectionFacets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).UpdateCollectionFacets(ctx, req.(*IdAndDict))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_UpdateResourceFacets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdAndDict)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).UpdateResourceFacets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/UpdateResourceFacets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).UpdateResourceFacets(ctx, req.(*IdAndDict))
	}
	return interceptor(ctx, in, info, handler)
}

func _WysteriaGrpc_UpdateLinkFacets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdAndDict)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WysteriaGrpcServer).UpdateLinkFacets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wysteria_grpc.WysteriaGrpc/UpdateLinkFacets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WysteriaGrpcServer).UpdateLinkFacets(ctx, req.(*IdAndDict))
	}
	return interceptor(ctx, in, info, handler)
}

var _WysteriaGrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wysteria_grpc.WysteriaGrpc",
	HandlerType: (*WysteriaGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCollection",
			Handler:    _WysteriaGrpc_CreateCollection_Handler,
		},
		{
			MethodName: "CreateItem",
			Handler:    _WysteriaGrpc_CreateItem_Handler,
		},
		{
			MethodName: "CreateVersion",
			Handler:    _WysteriaGrpc_CreateVersion_Handler,
		},
		{
			MethodName: "CreateResource",
			Handler:    _WysteriaGrpc_CreateResource_Handler,
		},
		{
			MethodName: "CreateLink",
			Handler:    _WysteriaGrpc_CreateLink_Handler,
		},
		{
			MethodName: "DeleteCollection",
			Handler:    _WysteriaGrpc_DeleteCollection_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _WysteriaGrpc_DeleteItem_Handler,
		},
		{
			MethodName: "DeleteVersion",
			Handler:    _WysteriaGrpc_DeleteVersion_Handler,
		},
		{
			MethodName: "DeleteResource",
			Handler:    _WysteriaGrpc_DeleteResource_Handler,
		},
		{
			MethodName: "FindCollections",
			Handler:    _WysteriaGrpc_FindCollections_Handler,
		},
		{
			MethodName: "FindItems",
			Handler:    _WysteriaGrpc_FindItems_Handler,
		},
		{
			MethodName: "FindVersions",
			Handler:    _WysteriaGrpc_FindVersions_Handler,
		},
		{
			MethodName: "FindResources",
			Handler:    _WysteriaGrpc_FindResources_Handler,
		},
		{
			MethodName: "FindLinks",
			Handler:    _WysteriaGrpc_FindLinks_Handler,
		},
		{
			MethodName: "PublishedVersion",
			Handler:    _WysteriaGrpc_PublishedVersion_Handler,
		},
		{
			MethodName: "SetPublishedVersion",
			Handler:    _WysteriaGrpc_SetPublishedVersion_Handler,
		},
		{
			MethodName: "UpdateVersionFacets",
			Handler:    _WysteriaGrpc_UpdateVersionFacets_Handler,
		},
		{
			MethodName: "UpdateItemFacets",
			Handler:    _WysteriaGrpc_UpdateItemFacets_Handler,
		},
		{
			MethodName: "UpdateCollectionFacets",
			Handler:    _WysteriaGrpc_UpdateCollectionFacets_Handler,
		},
		{
			MethodName: "UpdateResourceFacets",
			Handler:    _WysteriaGrpc_UpdateResourceFacets_Handler,
		},
		{
			MethodName: "UpdateLinkFacets",
			Handler:    _WysteriaGrpc_UpdateLinkFacets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wysteria.grpc.proto",
}

func init() { proto.RegisterFile("wysteria.grpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1059 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0x5b, 0x73, 0x1b, 0x35,
	0x14, 0xce, 0xda, 0xb9, 0xf9, 0x24, 0x4e, 0x8d, 0x9c, 0x49, 0x94, 0x65, 0x18, 0x32, 0xdb, 0x04,
	0x0c, 0x05, 0x3f, 0xa4, 0xd0, 0xd2, 0x90, 0x36, 0x34, 0x71, 0x5d, 0x0c, 0x99, 0x90, 0x3a, 0x09,
	0x50, 0x6e, 0x61, 0xb3, 0xab, 0x94, 0xa5, 0xbe, 0x8d, 0x24, 0x03, 0x7e, 0xe6, 0x0f, 0xf0, 0xc0,
	0x9f, 0xe0, 0xb7, 0x31, 0x7d, 0xe4, 0x9d, 0x91, 0xb4, 0xab, 0x5d, 0x6f, 0xb4, 0xb6, 0x49, 0x26,
	0xc3, 0x9b, 0x75, 0x39, 0xdf, 0xd1, 0xf7, 0x9d, 0xef, 0x48, 0x6b, 0x28, 0xff, 0x3a, 0x60, 0x9c,
	0xd0, 0xc0, 0xad, 0xbe, 0xa0, 0x3d, 0xaf, 0xda, 0xa3, 0x5d, 0xde, 0x45, 0xc5, 0x68, 0xf2, 0x4c,
	0x4c, 0x3a, 0x9f, 0xc2, 0x7c, 0xc3, 0x7f, 0xdc, 0xf1, 0x0f, 0xfb, 0x6d, 0xb4, 0x04, 0xb9, 0x86,
	0x8f, 0x7f, 0x5c, 0xb7, 0x2a, 0x85, 0x66, 0xae, 0xe1, 0x23, 0x0c, 0x73, 0x5f, 0x12, 0xca, 0x82,
	0x6e, 0x07, 0xfb, 0xeb, 0x56, 0x65, 0xa6, 0x19, 0x0d, 0x11, 0x82, 0xe9, 0x13, 0xf2, 0x1b, 0xc7,
	0x44, 0xee, 0x95, 0xbf, 0x9d, 0x3f, 0x2d, 0x28, 0x48, 0xa8, 0x5a, 0xe0, 0xf1, 0x4b, 0x58, 0x3b,
	0x30, 0x5b, 0x77, 0x3d, 0xc2, 0x19, 0x76, 0xd7, 0xf3, 0x95, 0x85, 0xad, 0x8d, 0xea, 0xd0, 0x39,
	0xaa, 0x3a, 0xb2, 0xaa, 0xb6, 0x3d, 0xe9, 0x70, 0x3a, 0x68, 0x86, 0x31, 0xf6, 0x03, 0x58, 0x48,
	0x4c, 0xa3, 0x12, 0xe4, 0x5f, 0x92, 0x01, 0xb6, 0x24, 0xba, 0xf8, 0x89, 0x96, 0x61, 0xe6, 0x17,
	0xb7, 0xd5, 0x27, 0x38, 0x27, 0xe7, 0xd4, 0x60, 0x3b, 0xf7, 0x91, 0xe5, 0xec, 0x8a, 0x83, 0x84,
	0xc7, 0xb1, 0xf4, 0x71, 0xde, 0x81, 0x19, 0x42, 0x69, 0x97, 0xe2, 0x67, 0xeb, 0x56, 0x65, 0x61,
	0xab, 0x9c, 0x3a, 0x8d, 0x20, 0xd4, 0x54, 0x3b, 0x1c, 0x5b, 0x71, 0xd5, 0x9c, 0x8f, 0x12, 0x9c,
	0x5f, 0x59, 0x00, 0xfb, 0xdd, 0x56, 0x8b, 0x78, 0x5c, 0xc8, 0xb2, 0x02, 0xb3, 0x47, 0x2e, 0x25,
	0x1d, 0x8e, 0xcf, 0xe4, 0xa6, 0x70, 0x14, 0x66, 0x9f, 0xd5, 0xd9, 0x11, 0x4c, 0x1f, 0xba, 0x6d,
	0x82, 0xe7, 0x14, 0x94, 0xf8, 0x8d, 0x1e, 0x6a, 0x81, 0x7e, 0x90, 0x02, 0x6d, 0xa6, 0x8e, 0x14,
	0xa7, 0x31, 0x29, 0x14, 0x13, 0x6a, 0x8e, 0x23, 0x74, 0x1d, 0x31, 0x7f, 0xcf, 0xc1, 0x74, 0x83,
	0x93, 0x76, 0x82, 0xe9, 0xa2, 0x81, 0x69, 0x51, 0x33, 0xb5, 0x61, 0x5e, 0xec, 0x3f, 0x19, 0xf4,
	0x08, 0x5e, 0x92, 0xb3, 0x7a, 0x2c, 0xed, 0xe5, 0xd2, 0xc0, 0xed, 0x70, 0x7c, 0x4b, 0x2e, 0x45,
	0x43, 0x74, 0x5f, 0x6b, 0x51, 0x92, 0x5a, 0xbc, 0x99, 0x36, 0x0b, 0x27, 0xed, 0xd1, 0x2a, 0x1c,
	0xdf, 0xa4, 0x0a, 0x7f, 0x5b, 0xba, 0x31, 0x12, 0x42, 0xac, 0x19, 0x84, 0xb0, 0xb5, 0x10, 0x2b,
	0x30, 0x7b, 0xd8, 0x6f, 0x9f, 0x13, 0x8a, 0x5f, 0x97, 0xad, 0x14, 0x8e, 0xd0, 0xb6, 0xa6, 0xfa,
	0x86, 0xa4, 0xea, 0xa4, 0x8e, 0x1c, 0xe6, 0x19, 0xcd, 0xf6, 0xe4, 0x26, 0xd9, 0xfe, 0x95, 0x83,
	0xf9, 0x26, 0x61, 0xdd, 0x3e, 0xf5, 0x48, 0x82, 0xee, 0xc6, 0x10, 0xdd, 0xc8, 0xd1, 0x9b, 0x09,
	0x47, 0x3b, 0xb0, 0x18, 0xc5, 0xc9, 0xfa, 0xbf, 0x25, 0xd7, 0x86, 0xe6, 0x42, 0x99, 0xde, 0x4e,
	0xfa, 0xe5, 0xa0, 0xeb, 0xb9, 0xc2, 0xe6, 0xb8, 0xa2, 0xfc, 0x12, 0x8d, 0xd1, 0xc7, 0x5a, 0xaa,
	0x0b, 0x29, 0xd5, 0xed, 0x14, 0xdf, 0x08, 0x78, 0xb4, 0x56, 0xa7, 0x37, 0xa9, 0xd5, 0x2b, 0x0b,
	0xa6, 0x0f, 0x82, 0xce, 0x4b, 0xad, 0xc7, 0x9d, 0x84, 0x1e, 0x8a, 0xeb, 0x7b, 0x9a, 0x6b, 0x09,
	0xf2, 0xc7, 0xd4, 0xc3, 0xef, 0x2b, 0xe0, 0x63, 0xea, 0x89, 0x99, 0x1a, 0xe3, 0xb8, 0xaa, 0x66,
	0x6a, 0x2c, 0xd9, 0x09, 0x2f, 0x8c, 0x9d, 0x20, 0x92, 0xfd, 0x8f, 0x7c, 0xff, 0xc8, 0x43, 0xe1,
	0x59, 0x9f, 0xd0, 0x41, 0x8d, 0x30, 0x2f, 0x61, 0x8e, 0x1d, 0x43, 0x2f, 0x3c, 0xd4, 0xc4, 0x37,
	0xa0, 0x18, 0xda, 0x3a, 0x6c, 0x89, 0x47, 0xb2, 0x25, 0x86, 0x27, 0x87, 0xae, 0x8e, 0xdd, 0xec,
	0xab, 0xe3, 0x93, 0xe1, 0xab, 0x23, 0x7e, 0x67, 0x1e, 0x1b, 0xdf, 0x19, 0x7d, 0x5a, 0xa3, 0x6a,
	0x51, 0xd9, 0xf6, 0x46, 0xd8, 0x78, 0xdf, 0x60, 0xe3, 0xa4, 0x6d, 0x6b, 0x29, 0xdb, 0x62, 0x98,
	0x13, 0x55, 0x12, 0xa5, 0x7e, 0xa2, 0xce, 0x1a, 0x0e, 0xa3, 0x15, 0x51, 0xf2, 0x7a, 0xbc, 0x52,
	0x63, 0xfc, 0x3a, 0x25, 0xb9, 0x00, 0xd0, 0x1c, 0x99, 0xd8, 0x77, 0x10, 0xb4, 0x03, 0x8e, 0x03,
	0x29, 0xb1, 0x1a, 0x88, 0x42, 0x7d, 0x71, 0x71, 0xc1, 0x08, 0xc7, 0x3f, 0xab, 0xcb, 0x48, 0x8d,
	0xd0, 0xbb, 0x90, 0x77, 0x5b, 0x2d, 0xfc, 0xb9, 0x54, 0x0e, 0x67, 0x29, 0xd7, 0x14, 0x9b, 0x9c,
	0x53, 0xc8, 0x37, 0x7c, 0x86, 0x6e, 0xab, 0x90, 0x2d, 0x19, 0xf2, 0xda, 0xa5, 0x47, 0x5d, 0xee,
	0x8d, 0xcd, 0xf8, 0xf5, 0xd8, 0xd7, 0x96, 0xc0, 0x42, 0xfc, 0xd2, 0x31, 0x74, 0x47, 0xc1, 0xdf,
	0x95, 0xf0, 0x6b, 0x99, 0x4f, 0x62, 0x2a, 0xcd, 0xf3, 0xb1, 0x69, 0x9e, 0xc3, 0x8c, 0x30, 0x13,
	0x43, 0x9b, 0x2a, 0xc1, 0x07, 0x32, 0x41, 0xd9, 0xf0, 0xce, 0xa4, 0xa0, 0xbf, 0x19, 0x0b, 0x7d,
	0x06, 0xf3, 0xa1, 0x91, 0x19, 0xaa, 0x28, 0xf4, 0x0f, 0x25, 0xfa, 0x8a, 0xf9, 0x6a, 0x4f, 0x25,
	0xf8, 0x76, 0x6c, 0x02, 0x17, 0x0a, 0x91, 0xf9, 0x44, 0x9f, 0xcb, 0x0c, 0xf7, 0x64, 0x86, 0xd5,
	0x8c, 0x1b, 0x31, 0x95, 0xe2, 0xbb, 0x49, 0xe4, 0x11, 0x56, 0xd4, 0xf2, 0xdc, 0x37, 0xca, 0x23,
	0xb6, 0xa4, 0xa0, 0xbf, 0x1f, 0x07, 0xbd, 0xf5, 0x0f, 0xc0, 0xe2, 0x57, 0xe1, 0xea, 0x53, 0xda,
	0xf3, 0xd0, 0x1e, 0x94, 0xf6, 0x29, 0x71, 0x39, 0x49, 0x7c, 0x48, 0x65, 0x57, 0xda, 0xbe, 0xec,
	0x31, 0x67, 0x0a, 0xdd, 0x03, 0x50, 0x18, 0xf2, 0xe3, 0xc4, 0x54, 0x46, 0x73, 0xdc, 0x1e, 0x14,
	0x55, 0x9c, 0x7e, 0xce, 0xcd, 0x35, 0xb2, 0x57, 0x4d, 0x9f, 0xab, 0x87, 0xfd, 0xb6, 0x33, 0x85,
	0x1e, 0xc1, 0x92, 0xc2, 0xd0, 0x8f, 0x64, 0x56, 0x19, 0xc6, 0x9c, 0x5d, 0x3e, 0x1c, 0x26, 0x8d,
	0xcd, 0x71, 0x3b, 0x50, 0xaa, 0x91, 0x16, 0x19, 0xd2, 0xed, 0xf2, 0x46, 0xdb, 0x54, 0x0b, 0x95,
	0x55, 0x45, 0x4b, 0xc5, 0x26, 0x8f, 0x7b, 0x00, 0x45, 0x15, 0x17, 0x29, 0x36, 0x79, 0xe8, 0x36,
	0x2c, 0xa9, 0x50, 0x2d, 0xd4, 0xe4, 0xb1, 0x9f, 0xc1, 0xad, 0x7a, 0xd0, 0xf1, 0x93, 0x57, 0xc3,
	0x5a, 0xd6, 0xfd, 0xc4, 0x6c, 0x3b, 0xd3, 0x3e, 0x4c, 0x16, 0xac, 0x20, 0xb0, 0x54, 0xff, 0x8f,
	0x40, 0x59, 0x36, 0xd8, 0x48, 0xc4, 0xd7, 0x60, 0x51, 0xc4, 0xeb, 0x26, 0x1f, 0x01, 0xb1, 0x6a,
	0xb6, 0x93, 0x40, 0xa9, 0x43, 0x51, 0xa0, 0xc4, 0x9d, 0x3c, 0x02, 0x06, 0x67, 0x18, 0x2a, 0xc1,
	0x46, 0xb5, 0xeb, 0x7f, 0x60, 0x23, 0x03, 0x9c, 0x29, 0xb4, 0x0b, 0xa5, 0xa3, 0xfe, 0x79, 0x2b,
	0x60, 0x3f, 0x11, 0x7f, 0x44, 0x4d, 0x33, 0x1a, 0x43, 0x02, 0x94, 0x8f, 0x09, 0x9f, 0x04, 0x23,
	0xa3, 0xb6, 0x75, 0x28, 0x9f, 0xf6, 0xfc, 0xb8, 0x09, 0xc3, 0xb7, 0x18, 0x67, 0xfd, 0x43, 0xcc,
	0xc2, 0xd9, 0x87, 0x92, 0xc2, 0x11, 0x85, 0xba, 0x2a, 0x48, 0x03, 0x56, 0x14, 0x48, 0xec, 0x99,
	0xab, 0x42, 0x3d, 0x85, 0x65, 0x05, 0x15, 0x95, 0xeb, 0xda, 0xc4, 0x44, 0xcd, 0xae, 0x08, 0x72,
	0x3e, 0x2b, 0xff, 0xfe, 0xdf, 0xfd, 0x37, 0x00, 0x00, 0xff, 0xff, 0x8a, 0xaa, 0x24, 0xc5, 0x15,
	0x10, 0x00, 0x00,
}
